services:
  portodotstack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      HOSTNAME: 0.0.0.0
    restart: unless-stopped