services:
  portodotstack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - intern-network
    environment:
      NODE_ENV: production
      PORT: 4000
      HOSTNAME: 0.0.0.0
    restart: unless-stopped

networks:
  intern-network:
    external: true